import {createContext} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import getConfig from 'next/config'
const { serverRuntimeConfig } = getConfig()
// function fromJSON (json) {
//   console.log(json)
//   if (Array.isArray(json._entries)) {
//     json._entries = json._entries.map(([id, entry]) => [id, fromJSON(entry)])
//     json._entries = new Map(json._entries)
//   } else {
//   }
//   console.log(json)
//   return json
// }
export default function Home({ manual }) {
  // console.log(manual)
  // manual = fromJSON(manual)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>arilychan</div>

      <div className="manual">
        <RecursiveManual section={manual} />
      </div>
      {/* <div>{JSON.stringify(manual)}</div> */}

    </div>
  )
}
function manualId(section){
  if (!section._id) {
    section._id = Math.random()
  }
  return section._id
}

function ManualNav({section}) {
  return <li href={manualId(section)}>{scetion._name || section._id}</li>
}

function ManualContent({scetion}) {
  return <section>
  <div className="title">{section._name || section._id || ''}</div>
  <li>
    <div className="section-body">
     {section._description && <div className="description">{section._description}</div>}
     {section._detail && <div className="detail">{section._detail}</div>}
     {section?._usages?.length >0 && <div className="usages">{section._usages.map(usage => <div className="usage">{usage}</div>)}</div>}
    </div>
  </li>
</section>
}

function RecursiveManual({ section, children }) {
  // const ctx = createContext(section)
  return <ctx.Provider value={children}>
    <children />
    {(() => {
    if (section._entries) {
      try {
        return <ul>
        {section._entries.map(([id, section]) => <RecursiveManual section={section} key={section._id} children={children}/>)}
      </ul>
      } catch (error) {
      }
    } else {
      console.log(section._entries)
    }
  })()}
  </div>
}

export function getServerSideProps() {
  return {
    props: {
      manual: serverRuntimeConfig.manual.json()
    }
  }
}