# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - publish
    paths:
      - 'utils/koishi-web-connect/package.json'
  workflow_dispatch:
    inputs:

jobs:
  publish-web-connect:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./utils/koishi-web-connect
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm install && npm install --only=dev
      - run: npm run build
      - run: npm publish '.'
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
