"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
exports.Act = void 0;
var Act;
(function (Act) {
    Act["Add"] = "add";
})(Act = exports.Act || (exports.Act = {}));
